name: voxcpm
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pydantic
  - tqdm
  - regex
  - addict
  - einops
  - simplejson
  - sortedcontainers
  - pip:
      - -r requirements.txt

